# Generated by Django 4.0.4 on 2022-05-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre_completo',
            new_name='name',
        ),
    ]
