# Generated by Django 4.0.4 on 2022-05-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprendimiento',
            old_name='nombre_emprendimiento',
            new_name='name',
        ),
    ]
