# Generated by Django 4.0.4 on 2022-05-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0002_rename_nombre_emprendimiento_emprendimiento_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprendimiento',
            options={'ordering': ['name'], 'verbose_name': 'Emprendimiento del Alumno', 'verbose_name_plural': 'Emprendimiento de Alumnos'},
        ),
    ]
