# Generated by Django 4.0.4 on 2022-05-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0004_emprendimiento_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendimiento',
            name='notas',
        ),
    ]
