# Generated by Django 4.0.4 on 2022-05-05 16:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0005_remove_emprendimiento_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='anotaciones',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
