# Generated by Django 4.0.4 on 2022-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre_completo',
            field=models.CharField(default=' ', max_length=250, verbose_name='Nombre Completo'),
        ),
    ]
