# Generated by Django 4.0.4 on 2022-05-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_persona_options_persona_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Alumno Emprendedor', 'verbose_name_plural': 'Alumnos Emprendedores'},
        ),
    ]
