# Generated by Django 4.0.4 on 2022-05-05 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.IntegerField(verbose_name='Número de Asiento')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('name', models.CharField(default=' ', max_length=250, verbose_name='Nota Explicativa')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Débito(+)/Crédito(-)')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.cuenta')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
