# Generated by Django 4.0.4 on 2022-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallecuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecuenta',
            name='asiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallecuenta',
            name='fecha',
            field=models.DateField(),
        ),
    ]
