# Generated by Django 4.0.4 on 2022-05-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detallecuenta', '0002_alter_detallecuenta_asiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecuenta',
            options={'ordering': ['name'], 'verbose_name': 'Partida Contable', 'verbose_name_plural': 'Partidas Contables'},
        ),
    ]
