# Generated by Django 4.0.4 on 2022-05-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprendimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(default=' ', max_length=250, verbose_name='Nombre Completo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendimiento.emprendimiento')),
            ],
        ),
    ]
