# Generated by Django 4.0.4 on 2022-05-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_domicilio_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Clientito'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_cliente',
            new_name='name',
        ),
    ]
