# Generated by Django 4.0.4 on 2022-05-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Customercito'},
        ),
    ]
