# Generated by Django 4.0.4 on 2022-05-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Customercito', 'verbose_name_plural': 'CUSTOMERCITOS'},
        ),
    ]
