# Generated by Django 4.0.4 on 2022-05-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0001_initial'),
        ('condicioniva', '0001_initial'),
        ('cliente', '0006_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'CLIENTE', 'verbose_name_plural': 'CLIENTES'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='domicilio',
            new_name='dom',
        ),
        migrations.AddField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='fotoalumno'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicioniva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condicioniva.condicioniva'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numconiva',
            field=models.CharField(default=' ', max_length=20, verbose_name='Número de CUIT'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numdoc',
            field=models.CharField(default=' ', max_length=15, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipodocumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipodocumento.tipodocumento'),
        ),
    ]
