# Generated by Django 4.0.4 on 2022-05-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_options_rename_domicilio_cliente_dom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='averiguar@email.ya', max_length=254, verbose_name='Email'),
        ),
    ]
