# Generated by Django 4.0.4 on 2022-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dom',
            field=models.CharField(default='Completar', max_length=250, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='desconocido@email.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numconiva',
            field=models.CharField(default='Completar', max_length=20, verbose_name='Número de CUIT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numdoc',
            field=models.CharField(default='Completar', max_length=15, verbose_name='Número de documento'),
        ),
    ]
