# Generated by Django 4.0.4 on 2022-05-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_cliente_tel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente del Emprendimiento', 'verbose_name_plural': 'Clientes de Emprendimientos'},
        ),
    ]
