# Generated by Django 4.0.4 on 2022-05-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprendimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=250, verbose_name='Proveedor')),
                ('domicilio', models.CharField(default=' ', max_length=250, verbose_name='Domicilio')),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendimiento.emprendimiento')),
            ],
        ),
    ]
