# Generated by Django 4.0.4 on 2022-05-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0002_alter_tipodocumento_options'),
        ('condicioniva', '0002_alter_condicioniva_options'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['name'], 'verbose_name': 'Proveedor del Emprendimiento', 'verbose_name_plural': 'Proveedores de Emprendimientos'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='fotoalumno'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condicioniva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condicioniva.condicioniva'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dom',
            field=models.CharField(default='Completar', max_length=250, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='desconocido@email.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numconiva',
            field=models.CharField(default='Completar', max_length=20, verbose_name='Número de CUIT'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numdoc',
            field=models.CharField(default='Completar', max_length=15, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tel',
            field=models.CharField(default=' ', max_length=250, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipodocumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipodocumento.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='name',
            field=models.CharField(default=' ', max_length=250, verbose_name='Cliente'),
        ),
    ]
