# Generated by Django 4.0.4 on 2022-05-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condicioniva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicioniva',
            options={'ordering': ['name'], 'verbose_name': 'Condición de I.V.A.', 'verbose_name_plural': 'Condiciones de I.V.A.'},
        ),
    ]
